nomad_download_url: https://releases.hashicorp.com/nomad/0.5.6/nomad_0.5.6_linux_amd64.zip
nomad_download_checksum: "sha256:3f5210f0bcddf04e2cc04b14a866df1614b71028863fe17bcdc8585488f8cb0c"
nomad_data_dir: /opt/nomad
