- name: update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true
  become_user: root

- name: install apt packages
  apt:
    name: "{{ item }}"
  become: true
  become_user: root
  with_items:
    - ca-certificates
    - curl
    - wget
    - unzip

- include: consul.yml
- include: consul-template.yml
